### ISSUE TITLE
Not working on MacOS.

### ISSUE THREAD

**Issue by CodeWithKamal** [aswinckr/figma-cursor#1]
![Screenshot 2024-10-14 at 2 24 08 PM](https://github.com/user-attachments/assets/ce7ac0e2-c257-462e-8325-2e59b943eb59)
I get this error when I try to open the plugin.

**Comment by aswinckr** [comment]
Hey! Let me look into this today! Thanks for reporting

**Comment by aswinckr** [comment]
Hey @CodeWithKamal . Looks like this could be a problem with Figma

The plugin seems to work fine for me

Try restarting figma? Maybe remove it once and try adding again?

Here's what i got from chatgpt
```
When encountering an error while loading a Figma plugin, it could be due to several reasons. Here are a few common troubleshooting steps:

Check Figma's Status:

Sometimes, Figma's servers may be experiencing issues. You can check Figma's status page to see if there are any ongoing outages.
Restart Figma:

Close and reopen Figma to refresh the environment, which may resolve temporary issues.
Update the Plugin:

Ensure the plugin is updated to the latest version. Plugin creators may release fixes for bugs or compatibility issues with newer versions of Figma.
Clear Cache and Reinstall the Plugin:

Go to the plugin panel, uninstall the plugin, clear your browser cache, or app cache, then reinstall the plugin to ensure that any corrupt files are removed.
Check Console Logs:

Open the console in Figma by going to View -> Open Console. This might give you more information about the error and help identify the issue.
Verify Permissions:

Some plugins require specific permissions to run. Make sure your browser or Figma desktop app isn't blocking the necessary permissions for the plugin to operate.
Check for Compatibility Issues:

Verify that the plugin is compatible with your current version of Figma. Some plugins may not work with certain updates or system environments.
If the issue persists, could you share more details on the error message? That can help narrow down the cause.
```

**Comment by CodeWithKamal** [comment]
nope still same error, restarted Figma and did everything.

**Comment by aswinckr** [comment]
Do you see any logs in the console?

Hit Cmd+I and can you share the console logs here please?

**Comment by CodeWithKamal** [comment]
yes, let me share it.

**Comment by CodeWithKamal** [comment]
I see this error:
```
vendor-core-893f98e48d1ec585.min.js.br:15 Error: Unable to load code: Error: Error invoking remote method 'web:getLocalFileExtensionSource': Error: ENOENT: no such file or directory, lstat '/Users/my-username/Documents/figma-cursor-main/dist/code.js'
    at eh (figma_app-98247404aee9dffa.min.js.br:128:373682)
    at async 9374-54463aa82ff32894.min.js.br:502:6081
    at async Promise.all (/design/WE0CKtbaUkj9ndFeQpb5xB/index 0)
    at async en (9374-54463aa82ff32894.min.js.br:502:6052)
    at async 9374-54463aa82ff32894.min.js.br:502:3549
```

here is the screenshot of console in Figma Desktop app for MacOS:
![Screenshot 2024-10-15 at 10 59 54 AM](https://github.com/user-attachments/assets/762efbe5-6bce-47f9-a9b0-8359ab919204)

**Comment by aswinckr** [comment]
Oh! You didn't build it!

You need to run `yarn build` on the terminal once 

Then try to import it it'll work

Will update the docs! Thanks for highlighting 🙂

**Comment by CodeWithKamal** [comment]
okay, let me run that. also I update my previous comment with screenshot if you need.

**Comment by aswinckr** [comment]
Okay! Let me know if this works. If not I'll check what else could be causing this difference in environments

**Comment by CodeWithKamal** [comment]
Yes, now it's working.

Since I don't use yarn, I had to install Yarn using npm. and also I had to run `yarn install && yarn build`.

![Screenshot 2024-10-15 at 11 05 41 AM](https://github.com/user-attachments/assets/aa22676e-0b41-4338-81fb-9d01819d7e78)

**Comment by CodeWithKamal** [comment]
Thank you for the help!

**Comment by aswinckr** [comment]
Awesome! Thanks 🙌🏽

I'll update in the docs
