### ISSUE TITLE
Any plan to publish this plugin?

### ISSUE THREAD

**Issue by zhigang1992** [aswinckr/figma-cursor#2]
This is such an amazing tool, much much better than taking screenshots!

Any plan on publishing it so that users don't have to build locally?

**Comment by aswinckr** [comment]
Thanks @zhigang1992 ! Published and currently under review :)

**Comment by aswinckr** [comment]
Here you go - https://www.figma.com/community/plugin/1434599500152464568/figma-to-cursor
